### ISSUE TITLE
Disabling cache doesn't work with requests_futures

### ISSUE THREAD

**Issue by MaxBareiss** [reclosedev/requests-cache#135]
When I use the `requests_cache` library with the `requests_futures` library, it works great. However, when I try to make a request without using the cache:

```
with requests_cache.disabled():
    rq = session.get(url)
```

it doesn't work:

```
rq.result().from_cache
True
```

**Comment by JWCook** [comment]
Here's what's happening:
* `requests_cache.install_cache()` patches out `requests.Session` with `requests_cache.CachedSession`
* When you create a `FuturesSession` object, that gets created as a subclass of `CachedSession` instead of `Session`
* `requests_cache.disabled()` will undo the session patch, but that won't affect your existing session object

Instead, use `with session.cache_disabled()`. And when using `requests-cache` with any other library that modifies `requests.Session`, it's going to be a lot easier to use `CachedSession` directly instead of using the global patching method (`install_cache()`). There are some related [examples in the docs here](https://requests-cache.readthedocs.io/en/latest/user_guide.html#usage-with-other-libraries-that-modify-requests-session).

Also, this may not be helpful if you have a specific reason for using `requests-futures`, but if you want async HTTP requests, using [aiohttp](https://docs.aiohttp.org) is a much better solution.

**Comment by JWCook** [comment]
I'll leave this issue open as a reminder to add an example to the docs specifically for `requests-futures`.
