### ISSUE TITLE
mongo backend doesnt let collection_name to be modified

### ISSUE THREAD

**Issue by rmnvncnt** [reclosedev/requests-cache#138]
It seems that the mongo backend forces a collection name parameter (`responses`) whereas `collection_name` is an optional parameter of `MongoCache` :
```
self.responses = MongoPickleDict(db_name, 'responses', options.get('connection'))
```
I think the intended behavior was :
```
self.responses = MongoPickleDict(db_name, options.get('collection_name'), options.get('connection'))
```

**Comment by JWCook** [comment]
Where do you see `collection_name` as an optional parameter of `MongoCache`? Also I see that this issue is a year and a half old now, so it's possible the code has changed since then.

I think the intent is for this to behave the same as all the other backends, which create two tables (or collections/namespaces/etc.) for 'responses' and 'urls' (redirects), respectively.

If you'd like to be able to modify those table names, that's something that should be added to all backend classes. Is that something you'd like to submit a PR for?

**Comment by JWCook** [comment]
Closing this issue for now. Please leave a comment if this is still something you or anyone else needs, and/or if you want to submit a PR for this.
