### ISSUE TITLE
Detect if requests-cache is active or not

### ISSUE THREAD

**Issue by shakeyourbunny** [reclosedev/requests-cache#144]
Is there a possibility to detect if requests-cache has been installed or not?

It is a bit awkward first to create a session object, then check if it has been tampered with requests-cache or not and then redoing the same again after enabling the cache.

It would be very convenient to have some sort of 
`
if not requests_cache.is_installed(....):
    requests_cache.install_cache(...)
`
to avoid re-installing it over and over again (and losing performance).

**Comment by JWCook** [comment]
If you want to submit a PR for this, I'd be happy to review and merge it.

I think this is one of the reasons why it's better to manage your own Session object rather than use the global monkey-patching functions. Also, it's simple enough to check whether a session is patched or not:
```python
isinstance(session, requests_cache.CachedSession):
```

Can you post an example in which you wouldn't know whether or not `requests.Session` has been patched? Is `install_cache()` being called by some other library, or in your own code?

**Comment by JWCook** [comment]
Done! There is now a `requests_cache.is_installed()` function.
