### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by JohnVillalovos** [reclosedev/requests-cache#167]
Noticed last commit was 14-Aug-2019. Which is almost 1.5 years ago as of today.

**Comment by hemna** [comment]
Would be nice if it was.  I was just looking for something like this, but not sure this project is usable now especially with py38?

**Comment by reinoldus** [comment]
I am using it with py38 and have no issues

**Comment by JWCook** [comment]
I have tested it with python 3.7, 3.8, and 3.9 (SQLite backend only), and appears to still work fine.

However, given that it's no longer maintained but still useful to a lot of projects out there, it is probably time for a community fork with a new owner + maintainers. Any takers?

Also, I started working on an async version, [aiohttp-client-cache](https://github.com/JWCook/aiohttp-client-cache), although it's not quite ready for general use yet, and it's made for `aiohttp` rather than `requests`.

**Comment by reinoldus** [comment]
The project is on code shelter. I guess that would be the most elegant way to gain access to it.

**Comment by JWCook** [comment]
Thanks for the heads up, @reinoldus. I wasn't familiar with Code Shelter. I'm looking into that now.

**Comment by JWCook** [comment]
After talking to the folks on Code Shelter, I now have collaborator permissions to the repo.

I don't plan on taking over full-time maintenance, but I can at least help review and merge PRs.

As for all the currently open issues, it would help if others would comment on ones you think are especially relevant and need attention, or create new issues to discuss other maintenance issues or suggestions.

**Comment by JWCook** [comment]
So hopefully this answers your question, @JohnVillalovos. The project can be as alive as you want it to be!

See the [v0.6 milestone](https://github.com/reclosedev/requests-cache/milestone/1) for current maintenance progress.

**Comment by JohnVillalovos** [comment]
Thanks @JWCook  !
