### ISSUE TITLE
Options for making an existing library easier to use with requests-cache

### ISSUE THREAD

**Issue by glensc** [reclosedev/requests-cache#289]
Similar to https://github.com/reclosedev/requests-cache/issues/260 need a guide/recommendation.

There's a library that uses `requests` directly without `session = requests.Session()`:
- https://github.com/moogar0880/PyTrakt/blob/3.1.0/trakt/core.py#L138

what would be a recommendation how to update those libraries to make them more friendly for requests_cache.

I think they should have simlary to Plex API, in constructor `session=None` that defaults to `session = requests.Session()`

but what about the code? just replace `requests.post` with `session.post`?

PS: please update the title so it be more meaningful and discoverable :)

**Comment by JWCook** [comment]
Your PR https://github.com/moogar0880/PyTrakt/pull/151 is pretty much what I would recommend. The only tricky part there is if you want to cache some requests but not others (like OAuth requests). You could use [URL patterns](https://requests-cache.readthedocs.io/en/v0.6.4/user_guide.html#url-patterns) to specify which ones to cache, if needed.

### Option 2
This may not be the best option for this particular case, but in general another option is to:
1. Add `requests-cache` as an optional dependency
2. Use ` requests_cache.CachedSession` if it's installed, and otherwise use a normal `requests.Session`:
```python
try:
    session = requests_cache.CachedSession(
        allowable_methods=('GET', 'POST'),
        urls_expire_after={...},
    )
except ImportError:
    session = requests.Session()
```

### Option 3
Alternatively, since there's already an `init()` method in there, you could maybe add a `session` parameter there so set a custom session. The only advantage there is that it would leave room for future refactoring in `trakt.core`, and then `init()` could be updated instead of breaking client code.

**Comment by glensc** [comment]
Sadly there's common entrypoint. trakt.init is not what it appears to be, it's for obtaining tokens. so, not useful. you can launch any of the methods, it will use module global state for things.

so, single-instance use only.

I'm not sure yeah, should such libraries be aware of reqests_cache themselves? seem safer for them not to add any dependency but support session object somehow.

**Comment by JWCook** [comment]
Okay, I see. You're right, it's not necessary for a library to be aware of requests-cache, and that can be done in the client application.

One use case for doing that is to provide some default cache settings that would be useful for that library, but not necessarily obvious to users. As a compromise, those details could also just be added to the library docs instead of making code changes.

For a more concrete example:
Personally, I plan to do something similar to option 3 in an API client library, except at the class level instead of module level. I want to add some pre-defined URL patterns, since I happen to know which API endpoints are useful to cache and which ones aren't. It will also accept a session object to use, if a user wants different settings, or wants to use something other than requests-cache. Another reason I want to do that is because some people use the library directly within a Jupyter notebook or similar environment, so instead of being wrapped in another application it pretty much _is_ the application at that point.

**Comment by JWCook** [comment]
@glensc Did this answer your question? And were you able to get requests-cache working with PyTrakt?

**Comment by glensc** [comment]
@JWCook yes:
- https://github.com/Taxel/PlexTraktSync/pull/355
