### ISSUE TITLE
Speeding up cache access

### ISSUE THREAD

**Issue by glensc** [reclosedev/requests-cache#295]
### The problem

I've looked at the debug logs and noticed a lot of repeated messages of opening sqlite database.

```
➔ grep -c 'Opening connection' last_update.log
3841
```

I'm not using patching, so, it's also happening with CachedSession usage, so this is called way too often:
- https://github.com/reclosedev/requests-cache/blob/5417069b431ec1e665bebe4c2bbeec0774d86bef/requests_cache/backends/sqlite.py#L94

### Expected behavior

Keep connection open, perhaps add some bulk operations support or preloading to memory support.

### Environment

- requests-cache version: `0.6.3`
- Python version: Irrelevant
- Platform: Irrelevant

**Comment by JWCook** [comment]
That has mostly been addressed in #213, which will be included in the next release. That change allows the connection to be left open instead of creating and closing one connection per transaction.

For SQLite, though, opening and closing a connection doesn't actually take much time, about **0.02 milliseconds** on my machine. Example:
```python
import sqlite3
from time import perf_counter

ITERATIONS = 100000

start = perf_counter()
for i in range(ITERATIONS):
    sqlite3.connect('test.db').close()
elapsed = perf_counter() - start
print(f'Average time per connection: {(elapsed/ITERATIONS)*1000} ms')
```

The majority of the time spent per operation is on `COMMIT`. If you have a block of code that you know will be caching several consecutive requests, you can use the [bulk_commit()](https://requests-cache.readthedocs.io/en/latest/modules/requests_cache.backends.html#requests_cache.backends.sqlite.DbDict.bulk_commit) contextmanager.

Hope that helps.

**Comment by glensc** [comment]
I'm not worried about write performance, but rather read performance.

**Comment by JWCook** [comment]
Sure, in that case try out the latest dev build, since that may already do what you want.

**Comment by glensc** [comment]
Would you mind adding instructions to readme how to use dev builds:
1. how to find build-id
2. how to install

**Comment by JWCook** [comment]
There are details here: https://requests-cache.readthedocs.io/en/stable/contributing.html#pre-releases

And you can find a full list of builds under 'Release History' on PyPI: https://pypi.org/project/requests-cache/#history

I'll add that link to the docs as well.

**Comment by glensc** [comment]
docs are ok.

but I still see with too many connections being opened:

```
➔ grep -c 'Opening connection' last_update.log
631
➔ pip3 list|grep cache
requests-cache    0.7.0.dev452
```

I'm testing on this branch:
- https://github.com/Taxel/PlexTraktSync/pull/311

perhaps for the connection re-use to happen, it's needed not to use global patching?

**Comment by glensc** [comment]
Tested, and if using CachedSession rather the global patching, the sqlite db is opened only once!

**Comment by JWCook** [comment]
> perhaps for the connection re-use to happen, it's needed not to use global patching?

Right, specifically with `install_cache()` + the static request functions (`requests.get()`, etc.), `requests` will create a new session object for each request, which also means one new db connection per request.

Like you found, either using `CachedSession` or `install_cache()` + `requests.Session` will do what you want.
