### ISSUE TITLE
ResourceWarning: unclosed ssl.SSLSocket with requests-cache and requests 2.6+

### ISSUE THREAD

**Issue by pudo** [reclosedev/requests-cache#413]
Since upgrading requests-cache to the latest release, I keep seeing these weird resource warnings:

```
ResourceWarning: unclosed <ssl.SSLSocket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.17.0.2', 39824), raddr=('83.118.217.137', 443)>
```

This does not make direct mention of the cache, so I'm sort of guessing here that it might be related. Feels like a dangling pointer in the handling of urllib3 somewhere. Please feel free to close the ticket if there's no correlation. Thanks for the amazing library!

### Environment
- requests-cache version: `0.8.1`
- Python version: `3.8`
- Platform: Ubuntu 20.04 (docker)

You can see this happen live here: https://github.com/pudo/opensanctions/runs/3640246226?check_suite_focus=true

**Comment by JWCook** [comment]
This is actually normal, due to connection pooling in `requests.Session`. It intentionally leaves connections open unless you explicitly close them, and I don't know of any case where you actually need to do that. I agree the message is a bit confusing, though, and sounds like a problem when it really isn't.

It's possible you weren't seeing this before due to using an older version of `requests`.

See these related issues:
* https://github.com/psf/requests/issues/3912
* https://github.com/psf/requests/issues/2963#issuecomment-169631513
* https://stackoverflow.com/questions/26563711

> Requests works very hard to prevent you closing a response. This is because it gets in the way of our connection pooling. If you really must close the connection, you need to close the underlying urllib3 connection: use `response.raw.close()`.

> The reason the resource warnings are back is because we're much better about not returning partially complete connections to the connection pool. The lack of warnings in 2.5.4 was actually symptomatic of a problem: weirdly, the warnings are an indication that everything is working as intended.

Since that's a warning (as in `warnings.warn()`) and not a log event (as in `logger.warning()`), you can suppress it with a filter using the python [`warnings`](https://docs.python.org/3/library/warnings.html) module:
```python
import warnings

warnings.simplefilter('ignore', ResourceWarning)
```

**Comment by JWCook** [comment]
I renamed the issue and added some details about this to the [Troubleshooting](https://requests-cache.readthedocs.io/en/latest/user_guide/troubleshooting.html#common-error-messages) section to make this more easily searchable for others.

**Comment by JWCook** [comment]
The only part I'm not sure about is why `ResourceWarning` isn't already filtered out in your case. It should be ignored by default. Maybe something in your environment is setting its own warning filter? That was the case with the `unittest` module in a couple of the issues linked above.

**Comment by pudo** [comment]
Wow! Thank you so much for this unbelievable response on my question. Thanks very very much for taking the time to provide such detailed information here. I'll just mute it and stop worrying :)
