### ISSUE TITLE
Add type hints for Response.from_cache and other extra attributes added to non-cached responses

### ISSUE THREAD

**Issue by Avasam** [reclosedev/requests-cache#516]
### The problem
The return type of `CachedSession.get` is `Response`  
This is probably the case with other methods as well

### Expected behavior
The return type of `CachedSession.get` to be `CachedResponse`

### Steps to reproduce the behavior
```py
from requests_cache.models.response import CachedResponse
response: CachedResponse = session.get(url, params=params, headers=headers)  # Wrong type assignment type error
is_from_cache = response.from_cache
```
![image](https://user-images.githubusercontent.com/1350584/151717324-4929e22b-4645-46ca-bc85-ae460a4436fe.png)

```py
response = session.get(url, params=params, headers=headers) 
is_from_cache = response.from_cache  # Member unknown type error
```
![image](https://user-images.githubusercontent.com/1350584/151717354-1adcb343-cab3-4e39-b9c1-6e7d82563603.png)

### Workarounds
Casting
```py
from typing import cast
from requests_cache.models.response import CachedResponse
response = cast(CachedResponse, session.get(url, params=params, headers=headers))
```

### Environment
- requests-cache version: 0.9.1
- Python version: 3.9
- Platform: Windows 10

**Comment by JWCook** [comment]
`requests.Response` is the correct type. The request functions can return either a `Response` (if not previously cached) or `CachedResponse`, which inherits from `Response`. You could also think of it as `Union[Response, CachedResponse]`, although a union with a subclass would be redundant.

The issue I see is that there is no typing information for the `from_cache` attribute set on `Response` objects. I didn't think it was worth it to type that since it was originally intended just for debugging purposes, although there might be valid uses for it in production code as well. On the library side, a possible solution for that would be to make an intermediate type that's a subclass of `Response` and superclass of `CachedResponse`. Doing that could potentially cause type errors for existing client code, but I'd still consider doing that.

On the client side, you could do something like:
```python
is_from_cache = getattr(response, 'from_cache', False)
```
Or just ignore it:
```python
is_from_cache = response.from_cache  # type: ignore
```

None of those solutions seem ideal, so I'm open to suggestions if you can think of a better way to handle that.

**Comment by Avasam** [comment]
I see, that makes sense if you simply add the `from_cache` attribute to the `Response` object.
Because of https://github.com/reclosedev/requests-cache/issues/514#issuecomment-1028421599 , I'm already testing for the existence of the attribute anyway.

I'm not sure what would be the best solution, but as far as I'm concerned, having typing information for `from_cache` would be preferable.

**Comment by JWCook** [comment]
After thinking about the wrapper class option a bit more (a new class in between `Response` and `CachedResponse`), that might not be such a terrible idea after all.

**Comment by JWCook** [comment]
Changes are now in master. Autocomplete screenshot:
![Screenshot from 2022-04-01 17-23-51](https://user-images.githubusercontent.com/419936/161349923-39c49ded-ac73-4a16-88d2-d2994afed2c9.png)
