### ISSUE TITLE
What happens to expired items?

### ISSUE THREAD

**Issue by toddpi314** [reclosedev/requests-cache#58]
Great module. Works as expected and is very performant.

When using with Sqlite, when a record expires, does the module manage purging those records in the underlying data-store?

if so, is there an API to some details of when we should expect the cycles to be spent to do that?
If not, it might be useful to post some code samples to the docs to help people manage the expired items, since the store sizes can get out of control pretty quickly with expired items.

Thanks!
Todd

**Comment by reclosedev** [comment]
It removes expired responses only when accessing the same url (+ params, method, etc).

I've added helper methods and notes to docs for manually removing old entries  (see referenced commits). Not sure when I'll be able to release it, before that you can use following code to remove old entries:
```python
from datetime import datetime, timedelta

import requests_cache

def remove_old_entries(cache, created_before):
    keys_to_delete = set()
    for key in cache.responses:
        try:
            response, created_at = cache.responses[key]
        except KeyError:
            continue
        if created_at < created_before:
            keys_to_delete.add(key)

    for key in keys_to_delete:
        cache.delete(key)


remove_old_entries(requests_cache.get_cache(), datetime.utcnow() - timedelta(hours=10))
```

MongoDB and Redis have TTL support, but it's not used in the library due to simple schema. So, the same "manual" cleanup is required.

**Comment by reclosedev** [comment]
Added to >= 0.4.11
