### ISSUE TITLE
convert a mongodb cache with serialized binaries to the new document format

### ISSUE THREAD

**Issue by masavini** [reclosedev/requests-cache#594]
hi,
is it possible to convert a mongodb cache with serialized binaries to the new [document format](https://github.com/reclosedev/requests-cache/issues/576)?

thanks!

**Comment by JWCook** [comment]
Yes, that's definitely possible. There's a [general example here](https://requests-cache.readthedocs.io/en/stable/user_guide/backends.html#exporting-to-a-different-backend), and here's an example for MongoDB in particular:
```python
from requests_cache import MongoCache

src_cache = MongoCache('http_cache', serializer='pickle')
dest_cache = MongoCache('new_cache')
dest_cache.update(src_cache)
```

That will copy contents into a separate database. I'd recommend keeping a backup, since those changes #(576) won't be released for awhile, and there may be more changes to the MongoDB backend before the next release.

If you want to test it out now, though, you can use the latest development build (`0.10.0-dev3`). Any feedback would be appreciated. Would you mind giving me some details on how you're using requests-cache, and why you chose MongoDB?

**Comment by JWCook** [comment]
I forgot one detail: cache keys will be different as well, to avoid conflicts between responses in different formats. So to recreate cache keys, you can do something like this:
```python
from requests_cache import MongoCache

src_cache = MongoCache('http_cache', serializer='pickle')
dest_cache = MongoCache('new_cache')
for response in src_cache.responses.values():
    dest_cache.save_response(response)
```

**Comment by masavini** [comment]
thanks for your hints, i decided to rebuild the whole cache, anyway.

going back to your previous questions, i'm sorry to inform you that my answers won't be a big study-case: this is my first python project (a scraper) and the very first time i use mongodb. i started using requests-cache to speed up development and testing, but i'm finding out it could be very useful in production, as well...

there are still quite some details about cache expiration i haven't properly got, but as someone said: "There are only two hard things in Computer Science: cache invalidation and naming things."

**Comment by JWCook** [comment]
> this is my first python project (a scraper)

Well in that case, congrats on picking the best programming language! Good luck with that.

> There are only two hard things in Computer Science: cache invalidation and naming things

Very true! Feel free to ask if you have specific questions about expiration.
