### ISSUE TITLE
Per-request cache timeout

### ISSUE THREAD

**Issue by mheppner** [reclosedev/requests-cache#95]
I haven't found any issues regarding this, but is there any way to set a timeout/expiration on a per-request basis? Can something with a context manager be added, similar to `.disabled()`? Maybe something like this:

```
requests_cache.install_cache(
    backend='sqlite',
    expire_after=300
)

with requests_cache.configure(expire_after=1000):
    res = requests.get('http://someurl.com')
```

The use case I have is to be able to cache certain requests much longer than everything else.

**Comment by Granitosaurus** [comment]
+1 for this. I couldn't find a way to set expiry per url, domain or anything else. There's only an option to set expiry on whole database which is rather limiting. 

To solve this I have to use several databases with varying expiration dates: short, medium and long.

**Comment by JWCook** [comment]
Currently the best way to accomplish this is to manage your own session object(s) instead of globally patching the session (with `requests_cache.install_cache()`).  Just use `requests_cache.CachedSession` in place of `requests.Session`. And, like @Granitosaurus mentioned, you can store cached responses with different expirations under a different cache name.

Example:
```python
from requests_cache import CachedSession

def get_foo():
    session = CachedSession(expire_after=10, cache_name='short_cache')
    return session.get('http://example.com/foo')


def get_bar():
    session = CachedSession(expire_after=1000, cache_name='long_cache')
    return session.get('http://example.com/bar')
```

This pattern would be made easier with the similar feature described in #108.
