### ISSUE TITLE
Serializing cache as a text file

### ISSUE THREAD

**Issue by dhimmel** [reclosedev/requests-cache#96]
I'm interested in using `requests-cache` in a [system](https://github.com/greenelab/manubot-rootstock) we're developing to fetch metadata for scholarly citations. All of our responses are text (i.e. no binary blobs).

In short, I'm interested in serializing the cache database to a text file. I'm hoping to achieve the following:

1. A serialization format for the cache (to store the cache between sessions) that is viewable in a text editor. Therefore, one can inspect the requests and their responses. Ideally, it would be easy to manually delete an entry via text editor.
2. The order of requests in the serialized cache file is deterministic. For certain applications, we may end up tracking the cache with git. Hence, it'd be awesome if the cache file doesn't get reorganized upon every usage, so the git diff is minimalist and sensible.

My initial thought would be to use the `memory` backend. 

```python
import requests
import requests_cache

# First time setup
requests_cache.install_cache(backend='memory', include_get_headers=True)
cache = requests_cache.get_cache()

# Do requests

# Export cache to file
# Assuming the actual cache is `cache.responses`?

# Subsequent uses
# Read in serialized cache.responses
```

Am I on the right track with this workflow? Is there a better backend for our needs? Is what we want even possible? I noticed `cache.responses` contains python objects, so it would have to be pickled rather than stored as JSON.

**Comment by JWCook** [comment]
@dhimmel I see this issue is a few years old now, but if this was something you would still find useful, there are some other users who want something similar in issue #30. If someone finishes the PR for that, that would be a good starting point, and an option for a different serialization format could be added onto that.

I'm not sure which one would best suit your needs, but a decent compromise might be BSON. That can serialize python objects, and you could use [bson-converter](https://atom.io/packages/bson-converter) for the Atom text editor to view and edit it in JSON format. I haven't used that personally, but it might be worth trying out.

**Comment by dhimmel** [comment]
Thanks @JWCook for following up. We ended up using the default sqlite cache without easy human readability of the database file. I'm still interested in this feature, although it's not a pressing need for Manubot at the moment.

**Comment by JWCook** [comment]
Thanks for the update. I'll close the issue for now, then, but if anyone else needs this feature or wants to work on a PR for it, I'll be happy to reopen this.

**Comment by JWCook** [comment]
For reference, this is now possible as of 0.7: https://requests-cache.readthedocs.io/en/latest/user_guide/serializers.html
